services:
  db:
    image: postgres:15
    restart: always
    container_name: encurtador-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: encurtador
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - encurtador_net

  usuario:
    build: ./usuario
    container_name: encurtador-usuario
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - encurtador_net
    env_file:
      - ./usuario/.env

  empresa:
    build: ./empresa
    container_name: encurtador-empresa
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - encurtador_net
    env_file:
      - ./empresa/.env

  url:
    build: ./url
    container_name: encurtador-url
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - encurtador_net
    env_file:
      - ./url/.env

volumes:
  pgdata:

networks:
  encurtador_net:
